version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: tracker_postgres
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: tracker_clickhouse
    restart: always
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native client
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  frontend:
    build:
      context: ./frontend
    container_name: tracker_frontend
    restart: always
    expose:
      - "8000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=db
      - DB_USER=user
      - DB_PASSWORD=password
    volumes:
      - ./frontend:/app
    command: [
      "uvicorn",
      "app:app",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--reload"
    ]

  backend:
    build:
      context: ./backend
    container_name: tracker_backend
    restart: always
    expose:
      - "8501"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=db
      - DB_USER=user
      - DB_PASSWORD=password
    volumes:
      - ./backend:/app
    command: [
      "uvicorn",
      "app:app",
      "--host", "0.0.0.0",
      "--port", "8501",
      "--reload"
    ]

  php:
    image: php:8.1-fpm
    container_name: tracker_php
    restart: always
    expose:
      - "9000"
    volumes:
      - ./frontend/landings:/var/www/landings

  nginx:
    build:
      context: ./nginx
    container_name: tracker_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/www/certbot
      - ./frontend/landings:/var/www/landings
    depends_on:
      - frontend
      - backend
      - php

volumes:
  postgres_data:
  clickhouse_data:
