version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: tracker_postgres
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password_password_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 3s
      retries: 20

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: tracker_clickhouse
    restart: always
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native client
    environment:
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: password_password_password
      CLICKHOUSE_DB: default
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.xml:ro
      - ./clickhouse/clickhouse-users.xml:/etc/clickhouse-server/users.xml:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 3s
      retries: 60

  frontend:
    build:
      context: ./frontend
    container_name: tracker_frontend
    restart: always
    expose:
      - "8000"
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_NAME=db
      - DB_USER=user
      - DB_PASSWORD=password_password_password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./frontend:/app
      - ./certbot-var:/var/www/certbot
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx:/var/www/nginx
    command: [
      "uvicorn",
      "app:app",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--reload"
    ]

  backend:
    build:
      context: ./backend
    container_name: tracker_backend
    restart: always
    expose:
      - "8501"
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_NAME=db
      - DB_USER=user
      - DB_PASSWORD=password_password_password
    volumes:
      - ./backend:/app
      - ./certbot-var:/var/www/certbot
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx:/var/www/nginx
    command: [
      "uvicorn",
      "app:app",
      "--host", "0.0.0.0",
      "--port", "8501",
      "--reload"
    ]

  php:
    image: php:8.1-fpm
    container_name: tracker_php
    restart: always
    expose:
      - "9000"
    volumes:
      - ./frontend/landings:/var/www/landings

  nginx:
    build:
      context: ./nginx
    container_name: tracker_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
      - ./certbot-var:/var/www/certbot
      - ./letsencrypt:/etc/letsencrypt
      - ./frontend/landings:/var/www/landings
      - ./nginx:/var/www/nginx
    depends_on:
      - frontend
      - backend
      - php
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  postgres_data:
  clickhouse_data:
