CREATE TABLE clicks_data (
    received_at DateTime DEFAULT now(),
    campaign_id Nullable(Int),
    offer_id Nullable(Int),
    ad_campaign_id String,
    status LowCardinality(String),
    external_id String,
    keyword String,
    landing_id String,
    language LowCardinality(String),
    url String,
    referrer String,
    browser LowCardinality(String),
    connection_type LowCardinality(String),
    currency LowCardinality(String),
    cost Nullable(Float32),
    profit Nullable(Float32),
    revenue Nullable(Float32),
    country LowCardinality(String),
    region LowCardinality(String),
    city LowCardinality(String),
    utm_campaign String,
    utm_creative String,
    utm_source String,
    visitor_id String,
    sub_id_1 String,
    sub_id_2 String,
    sub_id_3 String,
    sub_id_4 String,
    sub_id_5 String,
    sub_id_6 String,
    sub_id_7 String,
    sub_id_8 String,
    sub_id_9 String,
    sub_id_10 String,
    traffic_source_name LowCardinality(String),
    os LowCardinality(String),
    isp LowCardinality(String),
    ip IPv4,
    is_using_proxy Nullable(Bool),
    is_bot Nullable(Bool),
    device_type LowCardinality(String),
    device_brand LowCardinality(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(received_at)
ORDER BY (received_at)
SETTINGS index_granularity = 8192;
