CREATE TABLE clicks (
    received_at DateTime DEFAULT now(),
    campaign_id String,
    ad_campaign_id String,
    affiliate_network_name LowCardinality(String),
    browser LowCardinality(String),
    browser_version String,
    connection_type LowCardinality(String),
    city LowCardinality(String),
    campaign_name LowCardinality(String),
    campaign_alias String,
    conversion_cost Nullable(Float64),
    conversion_profit Nullable(Float64),
    conversion_revenue Nullable(Float64),
    conversion_sale_time Nullable(DateTime),
    conversion_time Nullable(DateTime),
    cost Nullable(Float64),
    country LowCardinality(String),
    creative_id String,
    visitor_id String,
    token String,
    tid String,
    subid String,
    sub_id_1 String,
    sub_id_2 String,
    sub_id_3 String,
    sub_id_4 String,
    sub_id_5 String,
    sub_id_6 String,
    sub_id_7 String,
    sub_id_8 String,
    sub_id_9 String,
    sub_id_10 String,
    visitor_code String,
    user_agent String,
    ts_id String,
    traffic_source_name LowCardinality(String),
    x_requested_with String,
    stream_id String,
    status LowCardinality(String),
    source String,
    search_engine LowCardinality(String),
    sample String,
    revenue Nullable(Float64),
    parent_campaign_id String,
    previous_status String,
    profit Nullable(Float64),
    random String,
    referrer String,
    region LowCardinality(String),
    os_version String,
    os LowCardinality(String),
    original_status String,
    operator LowCardinality(String),
    offer_value String,
    keyword String,
    landing_id String,
    language LowCardinality(String),
    offer String,
    offer_id String,
    offer_name String,
    isp LowCardinality(String),
    is_using_proxy Nullable(Bool),
    ip IPv4,
    is_bot Nullable(Bool),
    from_file String,
    external_id String,
    device_type LowCardinality(String),
    current_domain String,
    date Nullable(Date),
    debug Nullable(Bool),
    destination String,
    device_brand LowCardinality(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(received_at)
ORDER BY (campaign_id, received_at)
SETTINGS index_granularity = 8192;
